// Dados de conteúdo da landing page DAP.IA

export const AREAS = [
  { k: "C", t: "Consumidor", d: "Cobranças indevidas, produtos com defeito, golpes e fraudes bancárias." },
  { k: "T", t: "Trabalhista", d: "Demissões, verbas rescisórias, horas extras e direitos do trabalhador." },
  { k: "F", t: "Família e Sucessões", d: "Divórcio, pensão, guarda, inventário e partilha de bens." },
  { k: "P", t: "Previdenciário", d: "Aposentadorias, auxílios, BPC e revisão de benefícios do INSS." },
  { k: "B", t: "Tributário", d: "Impostos, execuções fiscais, parcelamentos e planejamento tributário." },
  { k: "R", t: "Criminal", d: "Defesa penal, inquéritos, audiências e direitos do acusado." },
  { k: "M", t: "Médico e Hospitalar", d: "Responsabilidade civil, prontuários e negativas de atendimento." },
  { k: "I", t: "Cível e Imobiliário", d: "Contratos, responsabilidade civil, distratos e regularização de imóveis." },
];

export const SLIDES = [
  {
    featured: true,
    cat: "Direito do Consumidor",
    title: "Busca e Apreensão de Veículo",
    desc: "A retomada do bem pela instituição financeira segue rito próprio do Decreto-Lei 911/69. Vícios na notificação ou na constituição em mora podem invalidar a medida.",
    points: [
      "Purgação da mora e restituição do veículo no prazo legal",
      "Nulidade por ausência de notificação válida do devedor",
      "Revisão de encargos e defesa contra alienação extrajudicial irregular",
    ],
    emblem: "911",
    refCap: "Decreto-Lei",
    refs: ["DL 911/69", "CDC", "STJ"],
    ask: "Tive meu veículo apreendido por atraso no financiamento, o que posso fazer?",
  },
  {
    featured: false,
    cat: "Direito Bancário",
    title: "Revisão de Juros e Contratos",
    desc: "Taxas em desacordo com a média de mercado, capitalização indevida e tarifas sem previsão legal são passíveis de revisão judicial, com restituição dos valores.",
    points: [
      "Cotejo com a taxa média divulgada pelo Banco Central",
      "Anatocismo e capitalização de juros sem pactuação expressa",
      "Repetição em dobro do indébito (art. 42, parágrafo único, CDC)",
    ],
    emblem: "51",
    refCap: "CDC · Artigo",
    refs: ["CDC Art. 42", "CDC Art. 51", "STJ"],
    ask: "Meus juros estão abusivos? Como faço para revisar?",
  },
  {
    featured: false,
    cat: "Direito Trabalhista",
    title: "Verbas e Rescisão Contratual",
    desc: "O encerramento do contrato de trabalho impõe ao empregador o pagamento das verbas devidas. Irregularidades na rescisão são exigíveis na Justiça do Trabalho.",
    points: [
      "Aviso prévio, saldo de salário, férias e 13º proporcionais",
      "Horas extras, adicionais e reflexos não pagos",
      "Reconhecimento de vínculo e verbas rescisórias omitidas",
    ],
    emblem: "CLT",
    refCap: "Consolidação",
    refs: ["CLT", "CF art. 7º", "TST"],
    ask: "Fui demitido e acho que meus direitos não foram pagos corretamente.",
  },
  {
    featured: false,
    cat: "Direito Previdenciário",
    title: "Benefícios do INSS",
    desc: "Indeferimentos, concessões com valor incorreto e revisões negadas administrativamente podem ser questionados, inclusive quanto ao tempo de contribuição.",
    points: [
      "Aposentadorias, auxílios e BPC/LOAS indevidamente negados",
      "Revisão da renda mensal inicial e do tempo de contribuição",
      "Restabelecimento de benefício cessado sem fundamentação",
    ],
    emblem: "8.213",
    refCap: "Lei",
    refs: ["Lei 8.213/91", "INSS", "TNU"],
    ask: "Meu benefício do INSS foi negado ou está com valor errado, o que fazer?",
  },
  {
    featured: false,
    cat: "Família e Sucessões",
    title: "Divórcio, Pensão e Inventário",
    desc: "Dissolução conjugal, guarda, alimentos e partilha de bens exigem tratamento técnico. O inventário regulariza a sucessão e a transferência do patrimônio.",
    points: [
      "Divórcio, partilha e definição de guarda e convivência",
      "Fixação, revisão e execução de alimentos",
      "Inventário judicial ou extrajudicial e partilha de herança",
    ],
    emblem: "CC",
    refCap: "Código Civil",
    refs: ["CC/2002", "CPC", "STJ"],
    ask: "Preciso de orientação sobre divórcio, guarda e pensão alimentícia.",
  },
  {
    featured: false,
    cat: "Cível & Golpes Bancários",
    title: "Fraudes e Negativação Indevida",
    desc: "Falhas na prestação do serviço bancário e inscrições indevidas em cadastros de inadimplentes geram dever de reparação, na forma da jurisprudência consolidada.",
    points: [
      "Responsabilidade objetiva do fornecedor por fortuito interno (Súmula 479)",
      "Baixa da negativação indevida e reparação por dano moral",
      "Recuperação de valores subtraídos em golpes de PIX e boleto",
    ],
    emblem: "479",
    refCap: "Súmula · STJ",
    refs: ["CDC", "Súmula 479", "Súmula 385"],
    ask: "Fui vítima de fraude bancária ou negativação indevida, quais meus direitos?",
  },
  {
    featured: false,
    cat: "Direito Tributário",
    title: "Execuções e Revisão Fiscal",
    desc: "Cobranças fiscais indevidas, execuções irregulares e a ausência de planejamento tributário oneram pessoas físicas e empresas de forma evitável.",
    points: [
      "Defesa em execução fiscal e embargos à cobrança indevida",
      "Restituição e compensação de tributos pagos a maior",
      "Parcelamentos, transações fiscais e planejamento tributário",
    ],
    emblem: "CTN",
    refCap: "Código Tributário",
    refs: ["CTN", "LEF 6.830/80", "STJ"],
    ask: "Recebi uma cobrança de imposto que considero indevida, como me defendo?",
  },
  {
    featured: false,
    cat: "Direito Médico & Criminal",
    title: "Erro Médico e Defesa Penal",
    desc: "Da responsabilização por falha na assistência à saúde à defesa técnica em matéria criminal, atuamos na proteção de direitos indisponíveis do cliente.",
    points: [
      "Responsabilidade civil por erro médico e negativa de atendimento",
      "Acesso a prontuários e apuração de conduta profissional",
      "Defesa penal em inquéritos, audiências e garantias do acusado",
    ],
    emblem: "CF 5º",
    refCap: "Constituição",
    refs: ["CF art. 5º", "CP", "CPP"],
    ask: "Sofri um erro médico ou preciso de defesa criminal, vocês atuam nisso?",
  },
];

export const DIFERENCIAIS = [
  { t: "Atendimento Inteligente", d: "Tributaristas, especialistas financeiros e consultores." },
  { t: "Recepcionista digital 24h", d: "Sistemas próprios de gestão e governança eficiente." },
  { t: "Inovação e produtividade", d: "Trabalho orientado à performance e à entrega de valor." },
  { t: "Ouve. Explica. Conecta.", d: "Trabalho orientado à performance e à entrega de valor." },
];
